// tools/list result: the tools with their input schemas.
function scr_devtools_mcp_tools_list()
{
    var _s = "{\"tools\":[";
    _s += "{\"name\":\"console_execute\",\"title\":\"Run console command\",\"description\":\"Run one DevTools console command in the running game, exactly as if typed into the F2 console, and return the lines it printed. Use 'help' to list all commands and 'help <command>' for the usage of a command. Commands act on the live game state and, except for a few such as help, need a loaded game - see game_load. Lines the console printed in red are prefixed with [error].\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"command\":{\"type\":\"string\",\"description\":\"The command line, e.g. 'help' or 'gold 500'.\"}},\"required\":[\"command\"]}},";
    _s += "{\"name\":\"console_read\",\"title\":\"Read console output\",\"description\":\"Return the most recent lines of the console output history, including output from commands typed by the player.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"lines\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":1000,\"default\":50,\"description\":\"How many of the newest lines to return.\"}}}},";
    _s += "{\"name\":\"screenshot\",\"title\":\"Screenshot\",\"description\":\"Capture the game window as a PNG image, including the HUD and menus. Takes one rendered frame, also while the game is minimized.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"max_width\":{\"type\":\"integer\",\"minimum\":0,\"default\":1280,\"description\":\"Downscale to at most this width in pixels, keeping the aspect ratio; 0 keeps the full resolution.\"}}}},";
    _s += "{\"name\":\"game_state\",\"title\":\"Game state\",\"description\":\"Report where the game is. phase is 'menu' (main menu), 'loading' (a room change, save load or menu fade is running), 'session' (a character is in the world), 'save_error' (a save failed to load) or 'other'. Also returns the room, whether the console is open and last_save - the save the main menu's Continue loads.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},";
    _s += "{\"name\":\"game_saves\",\"title\":\"List saves\",\"description\":\"List the characters and their saves, newest first like the in-game load menu: save folder, type (save, autosave or exitsave), date, location, and whether the game can load it - with the reason when it cannot.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},";
    _s += "{\"name\":\"game_load\",\"title\":\"Load save\",\"description\":\"Load a save, from the main menu or from a session - a running session is dropped without saving. Returns once loading has started; follow with game_wait for phase 'session'. Without arguments it loads last_save, like the main menu's Continue; with only character, that character's newest save. Exit saves are refused unless allow_exitsave is true, because the game deletes an exit save once it is loaded.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"character\":{\"type\":\"string\",\"description\":\"Character folder from game_saves, e.g. 'character_1'.\"},\"save\":{\"type\":\"string\",\"description\":\"Save folder from game_saves, e.g. 'autosave_1'.\"},\"allow_exitsave\":{\"type\":\"boolean\",\"default\":false,\"description\":\"Allow loading an exit save, which the game then deletes.\"}}}},";
    _s += "{\"name\":\"game_wait\",\"title\":\"Wait for phase\",\"description\":\"Wait until the game reaches a phase - 'menu' after the game starts, 'session' after game_load - and return the game state. Fails when the save failed to load, or when the timeout runs out: that text starts with 'timeout:', and calling again keeps waiting.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"phase\":{\"type\":\"string\",\"enum\":[\"menu\",\"session\"],\"description\":\"The phase to wait for.\"},\"timeout\":{\"type\":\"number\",\"minimum\":0,\"maximum\":50,\"default\":30,\"description\":\"Seconds to wait at most.\"}},\"required\":[\"phase\"]}},";
    _s += "{\"name\":\"game_event\",\"title\":\"Run event\",\"description\":\"Run one event of an instance with event_perform, the way the game's own code triggers events: GUI actions are user events (user event 0 of o_gui_button_inventory opens the inventory), world objects react to mouse events, key handlers are KeyPress events. Only the event's code runs - a Destroy event does not destroy the instance, and code that polls the keyboard or mouse still reads the real devices, so to click a GUI element use game_click. Nothing happens when the object has no such event, neither its own nor inherited; the decompiled file gml_Object_<object>_<Event>_<number>.gml shows what an event does. Events run for real: do not run ones that exit, save or sleep. A GML error stops the game in an error dialog.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"target\":{\"type\":[\"string\",\"integer\"],\"description\":\"An object name such as 'o_gui_button_inventory', or an instance id: 100234, '#100234' or '#ref 100234' as the console command getinstances prints it. An object with several instances needs all or an instance id; the reply lists them, with button labels.\"},\"event\":{\"type\":\"string\",\"description\":\"The event as in the decompiled file names: 'Other_10' (user event 0), 'Mouse_4' (left press), 'KeyPress_27' (Escape), 'Alarm_0', 'Step_0' - or 'user_N' for user event N. A bare type such as 'Alarm' takes its number from number.\"},\"number\":{\"type\":\"integer\",\"minimum\":0,\"description\":\"The event number, when event is a bare type.\"},\"all\":{\"type\":\"boolean\",\"default\":false,\"description\":\"Run the event on every instance of the object.\"}},\"required\":[\"target\",\"event\"]}},";
    _s += "{\"name\":\"game_click\",\"title\":\"Click\",\"description\":\"Click an instance the way a player's click reaches it, without the real cursor. GUI elements that take clicks - buttons, HUD buttons, menu entries - get the GUI controller's sequence: enter, press, release, leave. Hidden ones are refused (game_event still runs their events), and a deactivated or cooling-down button ignores the click; the reply says so. Other instances get the press and release mouse events through scr_cursorInteract, the game's own click simulation: clicking a friendly NPC walks the player over to talk, as a real click does. World objects may still check the real cursor, though - an NPC ignores the click while the real cursor rests on a window or the HUD. Clicks are real: do not click buttons that exit, save or sleep. Check the effect with screenshot or game_state.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"target\":{\"type\":[\"string\",\"integer\"],\"description\":\"An object name such as 'o_gui_button_inventory', or an instance id: 100234, '#100234' or '#ref 100234' as the console command getinstances prints it. An object with several instances needs an instance id; the reply lists them, with button labels.\"},\"button\":{\"type\":\"string\",\"enum\":[\"left\",\"right\"],\"default\":\"left\",\"description\":\"The mouse button.\"}},\"required\":[\"target\"]}}";
    _s += "]}";
    return _s;
}
