function scr_console_drop_help()
{
    var _lang = global.language;
    if (_lang == 1)
    {
        return [["drop [target...] [id | name | [slot rarity... lvl]] [amount] [condition...] [durability]", green], ["Создает в мире предмет с заданными параметрами и кидает его возле игрока.", gray], ["Если в параметре задается слот, выпадает случайный предмет для этого слота.", gray], ["В параметр slot так же можно ввести редкость и уровень предмета в формате 'drop slot legendary 30'.", gray], ["Опции:", white], ["inv: Создает предмет в инвентаре игрока (необязательный параметр)", gray], ["id: Идентификатор предмета.", gray], ["name: Имя предмета. (Пробел в названии файла заменяется знаком '_')", gray], ["slot: Тип предмета.", gray], ["\tcommon: Обычная редкость.", gray], ["\tunique:  Уникальная редкость.", gray], ["\tlegendary:  Легендарная редкость.", gray], ["\t\tlvl: Уровень выпадающего предмета в или max чтобы выбрать все.", gray], ["\t\t\tЕсли заданного уровня  оружия не существует округляет число в меньшую сторону.(по умолчанию max)", gray], ["amount: Количество выпадаемых предметов (по умолчанию 1)", gray], ["condition...: Состояние предмета. Вместо названия идентификатора разрешается вводить цифры в диапазоне 0-3 (по умолчанию common)", gray], ["\tcommon: Обычное состояние (обычный фон)(по умолчанию)", gray], ["\tuncommon: Необычное состояние (синий фон)", gray], ["\trare: Редкое состояние (зеленый фон)", gray], ["\tcurse: Проклятое состояние (темный фон и значок черепа)", gray], ["durability: Прочность предмета в процентах. (по умолчанию 100)", gray]];
    }
    if (_lang == 3)
    {
        return [["drop [target...] [id | name | [slot rarity... lvl]] [amount] [condition...] [durability]", green], ["在世界中生成一个带指定参数的物品并丢在玩家身旁。", gray], ["若指定槽位则掉落该槽位的随机物品。", gray], ["槽位参数也支持稀有度与等级，格式：'drop slot legendary 30'。", gray], ["选项：", white], ["inv: 在玩家背包中生成物品（可选参数）。", gray], ["id: 物品标识。", gray], ["name: 物品名称。（文件名中的空格用 '_' 代替）", gray], ["slot: 物品槽位类型。", gray], ["\tcommon: 普通稀有度。", gray], ["\tunique: 独特稀有度。", gray], ["\tlegendary: 传说稀有度。", gray], ["\t\tlvl: 掉落物品的等级，输入 max 则选取全部。", gray], ["\t\t\t若指定等级不存在对应武器，则向下取整。（默认 max）", gray], ["amount: 掉落物品数量（默认 1）。", gray], ["condition...: 物品状态。允许输入 0-3 的数字代替状态名（默认 common）。", gray], ["\tcommon: 普通状态（普通底色）（默认）。", gray], ["\tuncommon: 优良状态（蓝色底色）。", gray], ["\trare: 稀有状态（绿色底色）。", gray], ["\tcurse: 诅咒状态（深色底色与骷髅图标）。", gray], ["durability: 物品耐久的百分比（默认 100）。", gray]];
    }
    return [["drop [target...] [id | name | [slot rarity... lvl]] [amount] [condition...] [durability]", green], ["Creates an item with the given parameters in the world and drops it near the player.", gray], ["If a slot is given, a random item for that slot drops instead.", gray], ["The slot parameter also accepts a rarity and item level: 'drop slot legendary 30'.", gray], ["Options:", white], ["inv: Creates the item in the player's inventory (optional).", gray], ["id: Item identifier.", gray], ["name: Item name. (Spaces in the file name are replaced with '_')", gray], ["slot: Item slot type.", gray], ["\tcommon: Common rarity.", gray], ["\tunique: Unique rarity.", gray], ["\tlegendary: Legendary rarity.", gray], ["\t\tlvl: Level of the dropped item, or max to pick all.", gray], ["\t\t\tIf no weapon exists at the given level the number rounds down (default max).", gray], ["amount: Number of items to drop (default 1).", gray], ["condition...: Item condition. Numbers 0-3 are accepted instead of condition names (default common).", gray], ["\tcommon: Common condition (plain background) (default).", gray], ["\tuncommon: Uncommon condition (blue background).", gray], ["\trare: Rare condition (green background).", gray], ["\tcurse: Cursed condition (dark background and skull icon).", gray], ["durability: Item durability in percent (default 100).", gray]];
}
